import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar is auto-generated from the docs/ folder structure.
// Each section folder carries a _category_.json (label, position, generated-index).
const sidebars: SidebarsConfig = {
  guidesSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
